name: 'Test Workflow'

on:
  workflow_dispatch:

permissions:
  actions: read
  contents: read
  id-token: write

defaults:
  run:
    shell: powershell

jobs:
  Initialization:
    needs: [ ]
    runs-on: [ windows-latest ]
    steps:   
      - name: Check if ACTIONS_RUNNER_DEBUG is enabled
        run: |
          try {
            Write-Output "${{ runner.debug }}"
          } catch {
            Write-Output "Error: $($_.Exception.Message)"
          }
          if (${{ runner.debug }} -eq 1) {
            Write-Output "Debug logging is enabled."
          } else {
            Write-Output "Debug logging is not enabled."
          }
